apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    {{- include "tripla-apps.labels" (dict "root" . "component" "backend") | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:
    {{- include "tripla-apps.selectorLabels" (dict "root" . "component" "backend") | nindent 4 }}