apiVersion: v1
kind: Service
metadata:
  name: terraform-parse
  labels:
    {{- include "tripla-apps.labels" (dict "root" . "component" "terraform-parse") | nindent 4 }}
spec:
  type: {{ .Values.terraformParse.service.type }}
  ports:
    - port: {{ .Values.terraformParse.service.port }}
      targetPort: http
  selector:
    {{- include "tripla-apps.selectorLabels" (dict "root" . "component" "terraform-parse") | nindent 4 }}